spring:
  application:
    name: paddling-admin-demo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.31.255.122:3306/paddling?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: paddling
    password: Aa123456*
#    url: jdbc:mysql://127.0.0.2:3306/moreco?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
#    username: moreco
#    password: moreco